configserver: true
bus: true

spring:
    profiles: cloud
eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.springbox-service-registry.credentials.uri:http://127.0.0.1:8761}/eureka
